# Data Preprocessing

In [1]:
import pandas as pd
import numpy as np

Load dataset

In [2]:
base_data = pd.read_csv(r"C:\Users\user\Documents\GitHub\Project-2-Unified Mentor\European_Bank.csv")

In [3]:
base_data.head()

,Year,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,2025,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2025,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,2025,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,2025,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,2025,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

Clean Dataset

In [4]:
# remove unnecessary columns
base_data.drop(columns = ['CustomerId', 'Surname'], inplace = True)

In [5]:
base_data.head()

,Year,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,2025,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2025,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,2025,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,2025,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,2025,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [7]:
!pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp311-cp311-win_amd64.whl (8.1 MB)
     ---------------------------------------- 8.1/8.1 MB 2.6 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.24.1 in m:\data analyst\python 3.11\lib\site-packages (from scikit-learn) (2.4.4)
Collecting scipy>=1.10.0
  Downloading scipy-1.17.1-cp311-cp311-win_amd64.whl (36.6 MB)
     ---------------------------------------- 36.6/36.6 MB 2.9 MB/s eta 0:00:00
Collecting joblib>=1.3.0
  Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
     -------------------------------------- 309.1/309.1 kB 6.4 MB/s eta 0:00:00
Collecting threadpoolctl>=3.2.0
  Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.5.3 scikit-learn-1.8.0 scipy-1.17.1 threadpoolctl-3.6.0

[notice] A new release of pip available: 22.3.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
# Encode Categorical Variables
# for Gender Label encoding is used as it has only two categories
from sklearn.preprocessing import LabelEncoder
base_data['Gender'] = LabelEncoder().fit_transform(base_data['Gender'])

# for Geography One hot encoding is used, more than two categories are present
base_data = pd.get_dummies(base_data, columns = ['Geography'], drop_first = True)

In [ ]:
base_data.head() # France can be predicted by the absence of Germany and Spain # Female is 0 and Male is 1.

,Year,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain
0,2025,619,0,42,2,0.00,1,1,1,101348.88,1,False,False
1,2025,608,0,41,1,83807.86,1,0,1,112542.58,0,False,True
2,2025,502,0,42,8,159660.80,3,1,0,113931.57,1,False,False
3,2025,699,0,39,1,0.00,2,0,0,93826.63,0,False,False
4,2025,850,0,43,2,125510.82,1,1,1,79084.10,0,False,True

In [11]:
# FEATURE ENGINEERING
base_data['Balance_to_Salary_ratio'] = base_data['Balance'] / base_data['EstimatedSalary']

base_data['Product_Density_Indicator'] = base_data['NumOfProducts']/ base_data['Age']

base_data['Engagement_product_indicator'] = base_data['NumOfProducts']*2 + base_data['HasCrCard'] + base_data['IsActiveMember']

base_data['Age_tenure_interaction'] = base_data['Age']*base_data['Tenure']

In [12]:
base_data.head()

,Year,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Balance_to_Salary_ratio,Product_Density_Indicator,Engagement_product_indicator,Age_tenure_interaction
0,2025,619,0,42,2,0.00,1,1,1,101348.88,1,False,False,0.000000,0.023810,4,84
1,2025,608,0,41,1,83807.86,1,0,1,112542.58,0,False,True,0.744677,0.024390,3,41
2,2025,502,0,42,8,159660.80,3,1,0,113931.57,1,False,False,1.401375,0.071429,7,336
3,2025,699,0,39,1,0.00,2,0,0,93826.63,0,False,False,0.000000,0.051282,4,39
4,2025,850,0,43,2,125510.82,1,1,1,79084.10,0,False,True,1.587055,0.023256,4,86

In [14]:
# Scale Numerical Features
from sklearn.preprocessing  import StandardScaler

cols = ['CreditScore', 'Age', 'Balance', 'EstimatedSalary', 'Balance_to_Salary_ratio']

scalar = StandardScaler()

base_data[cols] = scalar.fit_transform(base_data[cols])

In [15]:
base_data.head()

,Year,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Balance_to_Salary_ratio,Product_Density_Indicator,Engagement_product_indicator,Age_tenure_interaction
0,2025,-0.326221,0,0.293517,2,-1.225848,1,1,1,0.021886,1,False,False,-0.035804,0.023810,4,84
1,2025,-0.440036,0,0.198164,1,0.117350,1,0,1,0.216534,0,False,True,-0.028930,0.024390,3,41
2,2025,-1.536794,0,0.293517,8,1.333053,3,1,0,0.240687,1,False,False,-0.022868,0.071429,7,336
3,2025,0.501521,0,0.007457,1,-1.225848,2,0,0,-0.108918,0,False,False,-0.035804,0.051282,4,39
4,2025,2.063884,0,0.388871,2,0.785728,1,1,1,-0.365276,0,False,True,-0.021154,0.023256,4,86